import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
  _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'system_default': 'System Default',
      'light_mode': 'Light Mode',
      'dark_mode': 'Dark Mode',
      'logout': 'Logout',
      'save': 'Save',
      'cancel': 'Cancel',
      'yes': 'Yes',
      'no': 'No',
      'delete': 'Delete',
      'confirm': 'Confirm',
      'loading': 'Loading...',
      'error': 'Something went wrong',
      'retry': 'Retry',
      'home': 'Home',
      'dashboard': 'Dashboard',
      'my_bookings': 'My Bookings',
      'notifications': 'Notifications',
      'support_chat': 'Support / Chat',
      'profile': 'Profile',
      'book_studio': 'Book a Studio',
      'app_name': 'GENZ Studios',
      'app_tagline': 'Professional Studio Booking',
      'welcome_back': 'Welcome back,',
      'login': 'Login',
      'register': 'Create Account',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'full_name': 'Full Name',
      'forgot_password': 'Forgot Password?',
      'continue_guest': 'Continue as guest',
      'already_account': 'Already have an account?',
      'no_account': "Don't have an account?",
      'verify_email': 'Verify Email',
      'resend_code': 'Resend Code',
      'confirm_account': 'Confirm Account',
      'booking_request': 'Booking Request',
      'our_studios': 'Our Studios',
      'no_bookings': 'No bookings yet',
      'no_bookings_sub': 'Your bookings will appear here',
      'status': 'Status',
      'pending': 'Pending',
      'approved': 'Approved',
      'rejected': 'Rejected',
      'total_price': 'Total Price',
      'equipment': 'Equipment',
      'send_booking': 'Send Booking Request',
      'booking_sent': 'Booking sent! ✅',
      'booking_failed': 'Failed. Try again.',
      'studio_booked': 'Studio already booked in this time slot',
      'accept_terms': 'Accept terms to continue',
      'invalid_dates': 'Invalid dates',
      'end_after_start': 'End time must be after start time',
      'confirm_cancel_booking': 'Are you sure you want to cancel this booking?',
      'booking_cancelled': 'Booking cancelled',
      'support_team': 'Support Team',
      'online': 'Online',
      'type_message': 'Type a message...',
      'no_messages': 'No messages yet',
      'start_conversation': 'Start the conversation!',
      'live_chat_unavailable': 'Live chat unavailable. Please submit a ticket.',
      'chat_disabled': 'Live chat disabled. Open a support ticket.',
      'no_notifications': 'No notifications yet',
      'no_notifications_sub': "We'll notify you of booking updates",
      'edit_profile': 'Edit Profile',
      'display_name': 'Display Name',
      'enter_name': 'Enter your name',
      'profile_saved': 'Profile saved ✅',
      'tap_photo': 'Tap photo to change',
      'save_changes': 'Save Changes',
      'new_ticket': 'New Support Ticket',
      'category': 'Category',
      'subject': 'Subject',
      'message': 'Message',
      'submit_ticket': 'Submit Ticket',
      'ticket_success': 'Ticket submitted successfully ✅',
      'ticket_failed': 'Failed to submit. Try again.',
      'fill_all_fields': 'Please fill in all fields',
      'support_tickets': 'Support Tickets',
      'no_tickets': 'No support tickets',
      'total': 'Total',
      'all': 'All',
      'delete_booking': 'Delete Booking?',
      'delete_all_data': 'Delete All Data?',
      'cannot_undo': 'This action cannot be undone.',
      'chat_enabled': 'Chat enabled',
      'chat_disabled_msg': 'Chat disabled',
      'enable_chat': 'Enable Chat',
      'disable_chat': 'Disable Chat',
      'confirm_booking_update': 'Confirm',
      'failed_update': 'Failed to update',
      'confirm_status': 'Confirm',
      'message_for_client': 'Message for client...',
      'booking_approved_msg': 'Your booking has been approved! ✅',
      'booking_rejected_msg': 'Sorry, your booking was rejected.',
      'delete_all': 'Delete All',
      'studios_count': '3 Studios',
      'instant_book': 'Instant Book',
      'support_247': '24/7 Support',
      'professional_booking': 'Professional studio booking\nat your fingertips',
      'profile_title': 'Profile',
      'bookings_stat': 'Bookings',
      'chat_stat': 'Chat',
      'active_status': 'Active',
      'off_status': 'Off',
      'account_section': 'Account',
      'bookings_support_section': 'Bookings & Support',
      'edit_profile_subtitle': 'Update name and photo',
      'my_bookings_subtitle': 'View and manage bookings',
      'open_ticket': 'Open Support Ticket',
      'open_ticket_subtitle': 'Report an issue or ask a question',
      'live_chat': 'Live Chat',
      'live_chat_subtitle': 'Chat with support team now',
      'tap_to_change': 'Tap photo to change',
      'display_name_label': 'Display Name',
      'enter_name_hint': 'Enter your name',
      'email_label': 'Email',
      'create_account_title': 'Create Account',
      'join_today': 'Join GENZ Studios today',
      'password_hint_info': 'Min 8 chars · Uppercase · Number · Symbol',
      'required_field': 'Required',
      'min_8_chars': 'Min 8 characters',
      'passwords_not_match': 'Passwords do not match',
      'invalid_email_msg': 'Invalid email',
      'reset_password_title': 'Reset Password',
      'new_password_title': 'New Password',
      'reset_password_sub': "Enter your email and we'll send a verification code.",
      'new_password_sub': 'Enter the code from your email and your new password.',
      'send_code_btn': 'Send Code',
      'code_sent': 'Verification code sent',
      'please_enter_email': 'Please enter your email',
      'reset_success': 'Password reset successfully',
      'resend_code_btn': 'Resend Code',
      'reset_password_btn': 'Reset Password',
      'chatbot_title': 'GENZ AI',
      'chatbot_subtitle': 'Your studio assistant',
      'clear_chat_title': 'Clear Chat?',
      'clear_chat_body': 'This will permanently delete the chat history.',
      'clear_btn': 'Clear',
      'chatbot_welcome': 'Ask GENZ AI anything!',
      'chatbot_welcome_sub': 'Studio availability, pricing, equipment and more.',
      'chatbot_input_hint': 'Ask GENZ AI...',
      'language_section': 'Language',
      'appearance_section': 'Appearance',
      'about_section': 'About',
      'app_version': 'Version',
      'employee': 'Employee',
      'client': 'Client',
      'studio_section': 'Studio',
      'select_studio': 'Select Studio',
      'personal_info': 'Personal Info',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'phone_number': 'Phone Number',
      'start_date_time': 'Start Date & Time',
      'end_date_time': 'End Date & Time',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'hour': 'Hour',
      'extra_equipment': 'Extra Equipment',
      'agree_terms': 'I agree to the terms and conditions',
      'required': 'Required',
      'invalid_email': 'Invalid email',
      'book': 'Book',
    },
    'ar': {
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'theme': 'المظهر',
      'system_default': 'النظام الافتراضي',
      'light_mode': 'الوضع الفاتح',
      'dark_mode': 'الوضع الداكن',
      'logout': 'تسجيل الخروج',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'yes': 'نعم',
      'no': 'لا',
      'delete': 'حذف',
      'confirm': 'تأكيد',
      'loading': 'جاري التحميل...',
      'error': 'حدث خطأ ما',
      'retry': 'إعادة المحاولة',
      'home': 'الرئيسية',
      'dashboard': 'لوحة التحكم',
      'my_bookings': 'حجوزاتي',
      'notifications': 'الإشعارات',
      'support_chat': 'الدعم / المحادثة',
      'profile': 'الملف الشخصي',
      'book_studio': 'احجز استوديو',
      'app_name': 'GENZ Studios',
      'app_tagline': 'حجز الاستوديو الاحترافي',
      'welcome_back': 'مرحباً بعودتك,',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'full_name': 'الاسم الكامل',
      'forgot_password': 'نسيت كلمة المرور؟',
      'continue_guest': 'المتابعة كزائر',
      'already_account': 'لديك حساب بالفعل؟',
      'no_account': 'ليس لديك حساب؟',
      'verify_email': 'تحقق من البريد الإلكتروني',
      'resend_code': 'إعادة إرسال الرمز',
      'confirm_account': 'تأكيد الحساب',
      'booking_request': 'طلب حجز',
      'our_studios': 'استوديوهاتنا',
      'no_bookings': 'لا توجد حجوزات بعد',
      'no_bookings_sub': 'ستظهر حجوزاتك هنا',
      'status': 'الحالة',
      'pending': 'قيد الانتظار',
      'approved': 'تمت الموافقة',
      'rejected': 'مرفوض',
      'total_price': 'السعر الإجمالي',
      'equipment': 'المعدات',
      'send_booking': 'إرسال طلب الحجز',
      'booking_sent': 'تم إرسال الحجز! ✅',
      'booking_failed': 'فشل الإرسال. حاول مجدداً.',
      'studio_booked': 'الاستوديو محجوز في هذا الوقت',
      'accept_terms': 'يجب الموافقة على الشروط للمتابعة',
      'invalid_dates': 'تواريخ غير صحيحة',
      'end_after_start': 'يجب أن يكون وقت الانتهاء بعد وقت البدء',
      'confirm_cancel_booking': 'هل أنت متأكد من إلغاء هذا الحجز؟',
      'booking_cancelled': 'تم إلغاء الحجز',
      'support_team': 'فريق الدعم',
      'online': 'متصل',
      'type_message': 'اكتب رسالة...',
      'no_messages': 'لا توجد رسائل بعد',
      'start_conversation': 'ابدأ المحادثة!',
      'live_chat_unavailable': 'المحادثة المباشرة غير متاحة. يرجى إرسال تذكرة دعم.',
      'chat_disabled': 'المحادثة المباشرة معطلة. افتح تذكرة دعم.',
      'no_notifications': 'لا توجد إشعارات بعد',
      'no_notifications_sub': 'سنُعلمك بتحديثات الحجز',
      'edit_profile': 'تعديل الملف الشخصي',
      'display_name': 'الاسم المعروض',
      'enter_name': 'أدخل اسمك',
      'profile_saved': 'تم حفظ الملف الشخصي ✅',
      'tap_photo': 'اضغط على الصورة للتغيير',
      'save_changes': 'حفظ التغييرات',
      'new_ticket': 'تذكرة دعم جديدة',
      'category': 'الفئة',
      'subject': 'الموضوع',
      'message': 'الرسالة',
      'submit_ticket': 'إرسال التذكرة',
      'ticket_success': 'تم إرسال التذكرة بنجاح ✅',
      'ticket_failed': 'فشل الإرسال. حاول مجدداً.',
      'fill_all_fields': 'يرجى ملء جميع الحقول',
      'support_tickets': 'تذاكر الدعم',
      'no_tickets': 'لا توجد تذاكر دعم',
      'total': 'الإجمالي',
      'all': 'الكل',
      'delete_booking': 'حذف الحجز؟',
      'delete_all_data': 'حذف جميع البيانات؟',
      'cannot_undo': 'لا يمكن التراجع عن هذا الإجراء.',
      'chat_enabled': 'تم تفعيل المحادثة',
      'chat_disabled_msg': 'تم تعطيل المحادثة',
      'enable_chat': 'تفعيل المحادثة',
      'disable_chat': 'تعطيل المحادثة',
      'confirm_booking_update': 'تأكيد',
      'failed_update': 'فشل التحديث',
      'confirm_status': 'تأكيد',
      'message_for_client': 'رسالة للعميل...',
      'booking_approved_msg': 'تمت الموافقة على حجزك! ✅',
      'booking_rejected_msg': 'عذراً، تم رفض حجزك.',
      'delete_all': 'حذف الكل',
      'studios_count': '3 استوديوهات',
      'instant_book': 'حجز فوري',
      'support_247': 'دعم 24/7',
      'professional_booking': 'حجز استوديو احترافي\nفي متناول يدك',
      'profile_title': 'الملف الشخصي',
      'bookings_stat': 'الحجوزات',
      'chat_stat': 'المحادثة',
      'active_status': 'نشط',
      'off_status': 'معطل',
      'account_section': 'الحساب',
      'bookings_support_section': 'الحجوزات والدعم',
      'edit_profile_subtitle': 'تحديث الاسم والصورة',
      'my_bookings_subtitle': 'عرض وإدارة الحجوزات',
      'open_ticket': 'فتح تذكرة دعم',
      'open_ticket_subtitle': 'الإبلاغ عن مشكلة أو طرح سؤال',
      'live_chat': 'محادثة مباشرة',
      'live_chat_subtitle': 'تحدث مع فريق الدعم الآن',
      'tap_to_change': 'اضغط على الصورة للتغيير',
      'display_name_label': 'الاسم المعروض',
      'enter_name_hint': 'أدخل اسمك',
      'email_label': 'البريد الإلكتروني',
      'create_account_title': 'إنشاء حساب',
      'join_today': 'انضم إلى GENZ Studios اليوم',
      'password_hint_info': '8 أحرف على الأقل · حرف كبير · رقم · رمز خاص',
      'required_field': 'مطلوب',
      'min_8_chars': '8 أحرف على الأقل',
      'passwords_not_match': 'كلمات المرور غير متطابقة',
      'invalid_email_msg': 'بريد إلكتروني غير صحيح',
      'reset_password_title': 'إعادة تعيين كلمة المرور',
      'new_password_title': 'كلمة مرور جديدة',
      'reset_password_sub': 'أدخل بريدك الإلكتروني وسنرسل لك رمز التحقق.',
      'new_password_sub': 'أدخل الرمز من بريدك الإلكتروني وكلمة المرور الجديدة.',
      'send_code_btn': 'إرسال الرمز',
      'code_sent': 'تم إرسال رمز التحقق',
      'please_enter_email': 'يرجى إدخال بريدك الإلكتروني',
      'reset_success': 'تم إعادة تعيين كلمة المرور',
      'resend_code_btn': 'إعادة إرسال الرمز',
      'reset_password_btn': 'إعادة تعيين كلمة المرور',
      'chatbot_title': 'GENZ AI',
      'chatbot_subtitle': 'مساعدك في الاستوديو',
      'clear_chat_title': 'مسح المحادثة؟',
      'clear_chat_body': 'سيتم حذف سجل المحادثة نهائياً.',
      'clear_btn': 'مسح',
      'chatbot_welcome': 'اسأل GENZ AI أي شيء!',
      'chatbot_welcome_sub': 'توفر الاستوديو، الأسعار، المعدات والمزيد.',
      'chatbot_input_hint': 'اسأل GENZ AI...',
      'language_section': 'اللغة',
      'appearance_section': 'المظهر',
      'about_section': 'عن التطبيق',
      'app_version': 'الإصدار',
      'employee': 'موظف',
      'client': 'عميل',
      'studio_section': 'الاستوديو',
      'select_studio': 'اختر الاستوديو',
      'personal_info': 'المعلومات الشخصية',
      'first_name': 'الاسم الأول',
      'last_name': 'اسم العائلة',
      'phone_number': 'رقم الهاتف',
      'start_date_time': 'تاريخ ووقت البدء',
      'end_date_time': 'تاريخ ووقت الانتهاء',
      'start_date': 'تاريخ البدء',
      'end_date': 'تاريخ الانتهاء',
      'hour': 'الساعة',
      'extra_equipment': 'معدات إضافية',
      'agree_terms': 'أوافق على الشروط والأحكام',
      'required': 'مطلوب',
      'invalid_email': 'بريد إلكتروني غير صحيح',
      'book': 'احجز',
    },
  };

  String translate(String key) {
    final langMap = _localizedValues[locale.languageCode];
    if (langMap == null) return _localizedValues['en']?[key] ?? key;
    return langMap[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(LocalizationsDelegate<AppLocalizations> old) => true;
}